/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 maserati.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Model(props) {
  const { nodes, materials } = useGLTF('/maserati.glb') 
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.CarPaint } material-color={props.exterior} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Rubber} />
        
        {/* <mesh geometry={nodes._2022_Maserati_MC20_100__2022_Maserati_MC20_Bianco_0.geometry} material={materials['2022_Maserati_MC20_Bianco']} position={[121.55018, 0.6288, -265.00076]} scale={0.11176} material-color={props.exterior}/>
        <mesh geometry={nodes._2022_Maserati_MC20_116__2022_Maserati_MC20_Interior_0.geometry} material={materials['2022_Maserati_MC20_Interior']} position={[121.55018, 0.6288, -265.00076]} scale={0.11176} material-color={props.interior}/> */}
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.MetalDark} material-color={props.exterior} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.PlasticDark}  />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.GlassLights}/>
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.GlassTextured} material-color={props.interior} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.GlassRedLights} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials.LightsChromeBMP}material-color={props.exterior}  />
        <mesh geometry={nodes.Mesh_9.geometry} material={materials.Undercarriage}  />

        <mesh geometry={nodes.Mesh_11.geometry} material={materials.GlassWinds}/>
        <mesh geometry={nodes.Mesh_12.geometry} material={materials.LicPlate} />
        <mesh geometry={nodes.Mesh_13.geometry} material={materials.PlasticDkGlossy} />
      </group>
      <mesh geometry={nodes.Undercarriage.geometry} material={materials['PlasticDark.001']} position={[0, 0.372, 1.651]} scale={0.001}  material-color={props.exterior}/>
      <group position={[0, 0.372, 1.651]} scale={0.001}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials['PlasticDark.001']} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials['Chrome.001']} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials['GlassRedLights.001']} />
        <mesh geometry={nodes.Mesh003_3.geometry} material={materials.GlassMatRedLights} />
        <mesh geometry={nodes.Mesh003_4.geometry} material={materials['LightsChromeBMP.001']} />
        <mesh geometry={nodes.Mesh003_5.geometry} material={materials.LightEmissiveWhite} />
        <mesh geometry={nodes.Mesh003_6.geometry} material={materials.GlassOrangeLights} />
        <mesh geometry={nodes.Mesh003_7.geometry} material={materials.GlassWhiteTail} />
      </group>
      <group scale={0.001}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials.PlasticDark} />
        <mesh geometry={nodes.Mesh004_2.geometry} material={materials.GlassLights} />
        <mesh geometry={nodes.Mesh004_3.geometry} material={materials.GlassRedLights} />
        <mesh geometry={nodes.Mesh004_4.geometry} material={materials.LightsChromeBMP} />
        <mesh geometry={nodes.Mesh004_5.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.Mesh004_6.geometry} material={materials.intAlcantaraGrey} />
        <mesh geometry={nodes.Mesh004_7.geometry} material={materials.intMetalSpeakers} />
        <mesh geometry={nodes.Mesh004_8.geometry} material={materials.intTexButtons} />
        <mesh geometry={nodes.Mesh004_9.geometry} material={materials.PlasticDkGlossy} />
        <mesh geometry={nodes.Mesh004_10.geometry} material={materials.intLeatherBlack}material-color={props.interior} />
        <mesh geometry={nodes.Mesh004_11.geometry} material={materials.intCarpet} />
        <mesh geometry={nodes.Mesh004_12.geometry} material={materials.intPlasticGrey} />
        <mesh geometry={nodes.Mesh004_13.geometry} material={materials.intMaseratiLogo} />
        <mesh geometry={nodes.Mesh004_14.geometry} material={materials.intAluminium} />
      </group>
      <group position={[0, 0.315, -0.831]} scale={0.001}>
        <mesh geometry={nodes.Mesh005.geometry} material={materials.PlasticDark} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Mesh005_2.geometry} material={materials.intAlcantaraGrey} />
        <mesh geometry={nodes.Mesh005_3.geometry} material={materials.intPlasticRed} />
        <mesh geometry={nodes.Mesh005_4.geometry} material={materials.intLeatherSeatsPattern} />
        <mesh geometry={nodes.Mesh005_5.geometry} material={materials.intLeatherBlack} />
        <mesh geometry={nodes.Mesh005_6.geometry} material={materials.intLeatherPerforated} />
        <mesh geometry={nodes.Mesh005_7.geometry} material={materials.intStitchesRed} />
        <mesh geometry={nodes.Mesh005_8.geometry} material={materials.intMaseratiLogoOPC} />
      </group>
      <group position={[0.38, 0.939, 0.43]} scale={0.001}>
        <mesh geometry={nodes.Mesh006.geometry} material={materials.PlasticDark} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials.intTexButtons} />
        <mesh geometry={nodes.Mesh006_2.geometry} material={materials.intLeatherSteeringWheel} />
        <mesh geometry={nodes.Mesh006_3.geometry} material={materials.intLeatherBlack} />
        <mesh geometry={nodes.Mesh006_4.geometry} material={materials.intLeatherPerforated} />
        <mesh geometry={nodes.Mesh006_5.geometry} material={materials.intCarbon} />
        <mesh geometry={nodes.Mesh006_6.geometry} material={materials.intAluminium} material-color={props.exterior} />
      </group>
      <group position={[0, 0.731, 0.29]} scale={0.001}>
        <mesh geometry={nodes.Mesh007.geometry} material={materials.MetalDark} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={materials.PlasticDark} />
        <mesh geometry={nodes.Mesh007_2.geometry} material={materials.GlassLights} />
        <mesh geometry={nodes.Mesh007_3.geometry} material={materials.intMetalSpeakers} />
        <mesh geometry={nodes.Mesh007_4.geometry} material={materials.intTexButtons} />
        <mesh geometry={nodes.Mesh007_5.geometry} material={materials.intTexDevices} />
        <mesh geometry={nodes.Mesh007_6.geometry} material={materials.PlasticDkGlossy} />
        <mesh geometry={nodes.Mesh007_7.geometry} material={materials.intLeatherBlack} />
        <mesh geometry={nodes.Mesh007_8.geometry} material={materials.intStitchesRed} />
        <mesh geometry={nodes.Mesh007_9.geometry} material={materials.intPlasticGrey} />
        <mesh geometry={nodes.Mesh007_10.geometry} material={materials.intMaseratiLogo} />
        <mesh geometry={nodes.Mesh007_11.geometry} material={materials.intTexButtonsGlossy} />
        <mesh geometry={nodes.Mesh007_12.geometry} material={materials.intCarbon} />
        <mesh geometry={nodes.Mesh007_13.geometry} material={materials.intAluminium} />
      </group>
      <group position={[0, 0.372, 1.651]} scale={0.001}>
        <mesh geometry={nodes.Mesh008.geometry} material={materials.PlasticDark} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Mesh008_2.geometry} material={materials.GlassLights} />
        <mesh geometry={nodes.Mesh008_3.geometry} material={materials.LightsChromeBMP} />
        <mesh geometry={nodes.Mesh008_4.geometry} material={materials['LightEmissiveWhite.001']} />
        <mesh geometry={nodes.Mesh008_5.geometry} material={materials.PlasticDkGlossy} />
        <mesh geometry={nodes.Mesh008_6.geometry} material={materials.HdLightsLens} />
      </group>
      <group position={[0.928, 0.827, 0.923]} scale={0.001}>
        <mesh geometry={nodes.Mesh012.geometry} material={materials.CarPaint} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={materials.PlasticDark} />
        <mesh geometry={nodes.Mesh012_2.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Mesh012_3.geometry} material={materials.GlassLights} />
        <mesh geometry={nodes.Mesh012_4.geometry} material={materials.LightsChromeBMP} />
        <mesh geometry={nodes.Mesh012_5.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.Mesh012_6.geometry} material={materials.intMetalSpeakers} />
        <mesh geometry={nodes.Mesh012_7.geometry} material={materials.intTexButtons} />
        <mesh geometry={nodes.Mesh012_8.geometry} material={materials.PlasticDkGlossy} />
        <mesh geometry={nodes.Mesh012_9.geometry} material={materials.intLeatherBlack} />
        <mesh geometry={nodes.Mesh012_10.geometry} material={materials.intStitchesRed} />
        <mesh geometry={nodes.Mesh012_11.geometry} material={materials.intChromeBump} />
        <mesh geometry={nodes.Mesh012_12.geometry} material={materials.intCarbon} />
      </group>
      <group position={[0.825, 0.357, 1.654]} scale={0.001}>
        <mesh geometry={nodes.Mesh019.geometry} material={materials.WheelTireBump} />
        <mesh geometry={nodes.Mesh019_1.geometry} material={materials.WheelMetalBlack}material-color={props.Wheel}  />
        <mesh geometry={nodes.Mesh019_2.geometry} material={materials.WheelBrakeDisk} material-color={props.Wheel} />
        <mesh geometry={nodes.Mesh019_3.geometry} material={materials.WheelPlasticBlackBolt}  />
        <mesh geometry={nodes.Mesh019_4.geometry} material={materials.WheelLogo} />
        <mesh geometry={nodes.Mesh019_5.geometry} material={materials.WheelAluminium} material-color={props.Wheel} />
      </group>
      <mesh geometry={nodes.mirror.geometry} material={materials.GlassWinds} position={[-0.928, 0.827, 0.923]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/maserati.glb')
