/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 truck.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/truck.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_1.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]}material-color={props.exterior} />
      <mesh geometry={nodes.model_0.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_2.geometry} material={materials['333333333333333333333333333333333333333333333333333333333333333']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_4.geometry} material={materials['Material.002']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} material-color={props.exterior}/>
      <mesh geometry={nodes.model_7.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} material-color={props.exterior}/>
      <mesh geometry={nodes.model_9.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} material-color={props.exterior}/>
      <mesh geometry={nodes.model_10.geometry} material={materials['Material.003']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} material-color={props.exterior}/>
      <mesh geometry={nodes.model_14.geometry} material={materials['Material.004']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} material-color={props.exterior} />
      <mesh geometry={nodes.model_18.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_28.geometry} material={nodes.model_28.material} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_37.geometry} material={nodes.model_37.material} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} material-color={props.exterior}/>
      <mesh geometry={nodes.model_38.geometry} material={nodes.model_38.material} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_58.geometry} material={materials['Material.005']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} material-color={props.interior} />
      <mesh geometry={nodes.model_59.geometry} material={materials['Material.005']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_60.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_61.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_62.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_64.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_67.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_68.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_71.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.model_72.geometry} material={materials['Material.001']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.006']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.007']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.008']} position={[10, -150, -200]} rotation={[Math.PI / 2, 0, -1.608]} scale={[0.412, 0.586, 0.586]} />
    </group>
  )
}

useGLTF.preload('/truck.glb')
